- name: Mongo Swarm - Checking Mongo Docker Stack
  shell: >
        docker stack ls | awk '{ if ($1 == "mongo") { print $1 } }'
  changed_when: false
  register: "mongo_stack"
  tags: [mongo-swarm]

- name: Mongo Swarm - Deploying Mongo Docker Stack
  shell: "docker stack deploy --compose-file /vagrant/ansible/roles/mongo-swarm/docker_stack.yml mongo"
  when: mongo_stack.stdout != 'mongo' and inventory_hostname == docker_swarm_primary_manager
  tags: [mongo-swarm]