docker_swarm_managers_ansible_group: 'swarm-managers'
docker_swarm_workers_ansible_group: 'swarm-workers'
docker_swarm_primary_manager: '{{ groups[docker_swarm_managers_ansible_group][0] }}'
mongo_docker_image: 'mongo:4.1.7-xenial'
docker_networks: ['mongo', 'mongos']

enable_shards: true
mongo_swarm_role_enabled: true