- include: alpine.yml
  when: ansible_os_family == "Alpine"

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: docker_started.yml

- include: users.yml
  when: >
      docker_config_users is defined and
      docker_config_users

- include: docker_compose.yml
  when: >
        docker_compose is defined and
        docker_compose